//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int CommentId { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int AdminSectionId { get; set; }
        public Nullable<int> ReplyCommentId { get; set; }
    
        public virtual AdminSection AdminSection { get; set; }
    }
}
